<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <OutputType>Exe</OutputType>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	    <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <None Update="Grimm.docx">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
        <PackageReference Include="DevExpress.RichEdit.Core" Version="24.2.*" />
    </ItemGroup>
</Project>